//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSWebApiEmpty.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BreweryEntities : DbContext
    {
        public BreweryEntities()
            : base("name=BreweryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Authentification> Authentification { get; set; }
        public DbSet<Recipes> Recipes { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<Beers> Beers { get; set; }
        public DbSet<Temperatures> Temperatures { get; set; }
    }
}
